### ISSUE TITLE
Empty file lists can't be edited it the UI

### ISSUE THREAD

**Issue by danielwoz** [xbapps/xbvr#1514]
Scene scrapers like sexbabesvr and lethalhardcorevr don't generate known file names and set the filenames_arr column to 'null'. This doesn't parse with browser console error:
vue.runtime.esm.js:3049 TypeError: Cannot read properties of null (reading 'push')
    at s.addRow (ListEditor.vue:39:17)
    at Yt (vue.runtime.esm.js:3017:30)
    at HTMLButtonElement.n (vue.runtime.esm.js:1815:20)
    at a._wrapper (vue.runtime.esm.js:7480:35)

I think this can be fixed multiple of ways, make sure all the scrapers put a valid value in that field, or otherwise ignore invalid values and create a new one when editing.

My current work around is simply:
sqlite3 main.db
UPDATE scenes SET filenames_arr = '["no_filename.mp4"]' where filenames_arr = 'null';

Of course this only works on scenes already scraped.

**Comment by danielwoz** [comment]
Fixed in https://github.com/xbapps/xbvr/pull/1480
