### ISSUE TITLE
Crash on VRHush scraper on 0.4.20

### ISSUE THREAD

**Issue by moToroTor** [xbapps/xbvr#1601]
I have two crashes, pasting both below.

```
panic: interface conversion: interface {} is nil, not string

goroutine 564334 [running]:
github.com/xbapps/xbvr/pkg/scrape.VRHush.func1(0xc0063c02a0)
	/go/src/pkg/scrape/vrhush.go:99 +0xe1b
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc009166780)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc009166690, 0xc00863bdf8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc0005b0700, 0xc006d02cc0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0005b0700, {0xa?, 0xc006b0e900?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc001bd3ce0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0005b0700, {0xc001f763c0, 0x2a}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc002f07680?, {0xc001f763c0?, 0xc001cd0d80?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func3(0xc001cd0d80)
	/go/src/pkg/scrape/vrhush.go:119 +0x17d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc001bd3c80)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc001bd2f90, 0xc00863c2c0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc0005b08c0, 0xc0009cb500)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0005b08c0, {0xa?, 0xc0000c3320?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc0032a7500, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0005b08c0, {0xc003cd92c0, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0005bb300?, {0xc003cd92c0?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc002b388a0)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc0032a74a0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0032a7140, 0xc00863c7d8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc0005b08c0, 0xc000859500)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0005b08c0, {0xa?, 0xc00724f440?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc007798540, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0005b08c0, {0xc00766e180, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000893880?, {0xc00766e180?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc007793140)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc0077984e0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc007798210, 0xc00863ccf0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc0005b08c0, 0xc0030022c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0005b08c0, {0xa?, 0xc004a80750?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc004e8f7d0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0005b08c0, {0xc004df4a20, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000892380?, {0xc004df4a20?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc004e89920)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc004e8f770)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc004e8f4a0, 0xc00863d208)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc0005b08c0, 0xc0009cbb40)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0005b08c0, {0xa?, 0xc0002319e0?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc0043833b0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0005b08c0, {0xc0042729c0, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc002f94480?, {0xc0042729c0?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc0043966c0)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc004383350)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc004383080, 0xc00863d720)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc0005b08c0, 0xc002f00740)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0005b08c0, {0xa?, 0xc0009ac120?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc00117c390, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0005b08c0, {0xc0001914a0, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc003014c00?, {0xc0001914a0?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc001175740)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc00117c330)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc00117c060, 0xc00863dc38)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc0005b08c0, 0xc002f00000)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0005b08c0, {0xa?, 0xc00302a5a0?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0xc000658e78?, 0xc003070150, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0005b08c0, {0x1011ce671, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0005b08c0?, {0x1011ce671?, 0x1f?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush(0x1000000000001?, 0x1, {0xc003f6a000, 0x1ce6, 0x2200}, 0xc000703740, {0x0, 0x0}, {0x0, 0x0})
	/go/src/pkg/scrape/vrhush.go:126 +0x2b1
created by github.com/xbapps/xbvr/pkg/tasks.runScrapers in goroutine 564169
	/go/src/pkg/tasks/content.go:124 +0x739
```
----

```
panic: interface conversion: interface {} is nil, not string

goroutine 567981 [running]:
github.com/xbapps/xbvr/pkg/scrape.VRHush.func1(0xc011ecfaa0)
	/go/src/pkg/scrape/vrhush.go:99 +0xe1b
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc011edced0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc011edcea0, 0xc009069df8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc002510e00, 0xc0005a55c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc002510e00, {0xa?, 0xc0108333b0?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc01082ec60, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc002510e00, {0xc010817ec0, 0x2a}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00165fb00?, {0xc010817ec0?, 0xc01082b620?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func3(0xc01082b620)
	/go/src/pkg/scrape/vrhush.go:119 +0x17d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc01082ec00)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc01082e0f0, 0xc00906a2c0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc002510fc0, 0xc0005debc0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc002510fc0, {0xa?, 0xc006112900?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc0068d00f0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc002510fc0, {0xc0061032c0, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0034b1a00?, {0xc0061032c0?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc0068caba0)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc0068d0090)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0068b3da0, 0xc00906a7d8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc002510fc0, 0xc0005de340)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc002510fc0, {0xa?, 0xc0027d78c0?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc005d5eae0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc002510fc0, {0xc005b46840, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0008a2800?, {0xc005b46840?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc005d18c00)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc005d5ea80)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc005d5e7b0, 0xc00906acf0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc002510fc0, 0xc0008a8e00)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc002510fc0, {0xa?, 0xc004af55f0?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc004df6720, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc002510fc0, {0xc0046501e0, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00165e380?, {0xc0046501e0?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc004def620)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc004df66c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc004df63f0, 0xc00906b208)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc002510fc0, 0xc000925900)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc002510fc0, {0xa?, 0xc000b122d0?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc001926f60, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc002510fc0, {0xc001d34a80, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00165e180?, {0xc001d34a80?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc001917c20)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc001926f00)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc001926c30, 0xc00906b720)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc002510fc0, 0xc000924ac0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc002510fc0, {0xa?, 0xc002480120?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc0006c4de0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc002510fc0, {0xc0039a9680, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc002500a80?, {0xc0039a9680?, 0x1?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush.func2(0xc002c99f80)
	/go/src/pkg/scrape/vrhush.go:110 +0x1c5
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x1030b7780?, 0xc0006c4d80)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0006c4ab0, 0xc00906bc38)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc002510fc0, 0xc0012b8bc0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc002510fc0, {0xa?, 0xc0024817a0?}, {0x1011662cb, 0x3}, 0x1, {0x0?, 0x0}, 0xc00002fe78?, 0xc003a22f90, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc002510fc0, {0x1011ce671, 0x43}, {0x1011662cb, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc002510fc0?, {0x1011ce671?, 0x1f?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRHush(0x1000000010000?, 0x1, {0xc002e80000, 0x1ce6, 0x2200}, 0xc00058f4a0, {0x0, 0x0}, {0x0, 0x0})
	/go/src/pkg/scrape/vrhush.go:126 +0x2b1
created by github.com/xbapps/xbvr/pkg/tasks.runScrapers in goroutine 567831
	/go/src/pkg/tasks/content.go:124 +0x739
```

**Comment by toshski** [comment]
Fixed by #1573 in next release

**Comment by moToroTor** [comment]
Could you provide nightlies or something? I don't quite understand your dev process and would rather something I can just run a makefile against.

**Comment by toshski** [comment]
The project isn't setup for nightlies and I am just a contributor to the site, Ie I don't have and extra permissions.  A new release is made and published, this depending on time availability and what changes have been submitted.  Until, then it's a waiting game.  

This fault might have pushed out new release sooner rather than later, except it only seems to affect a very small number of users.

If you are using docker, someone has setup their own nighties at ghcr.io/coolmintchocolate/xbvr:latest
