### ISSUE TITLE
segmentation violation when generation previews

### ISSUE THREAD

**Issue by wheresmytissue** [xbapps/xbvr#1615]
I've been getting this error from time to time when generating previews.
Let me know if you need additional info for debugging.  Looks like its during this function [call](https://github.com/xbapps/xbvr/blob/20ed68aeca9183d749f0e9d84e177253ba29505e/pkg/api/tasks.go#L205)

log is below

`time="2024-01-31T04:40:24Z" level=warning msg="exit status 1"
time="2024-01-31T04:40:24Z" level=info msg="Rendering slr-11924"
time="2024-01-31T04:40:25Z" level=warning msg="exit status 1"
time="2024-01-31T04:40:25Z" level=info msg="Rendering BUZ-052"
time="2024-01-31T04:40:25Z" level=warning msg="exit status 1"
time="2024-01-31T04:40:25Z" level=info msg="Rendering realjam-vr-104"
time="2024-01-31T04:40:55Z" level=info msg="Rendering slr-11518"
time="2024-01-31T04:40:55Z" level=warning msg="exit status 1"
time="2024-01-31T04:40:55Z" level=info msg="Rendering realjam-vr-103"
time="2024-01-31T04:41:26Z" level=info msg="Rendering sexbabesvr-271"
time="2024-01-31T04:43:22Z" level=warning msg="exit status 69"
time="2024-01-31T04:43:22Z" level=info msg="Rendering 18vr-324776"
time="2024-01-31T04:43:27Z" level=warning msg="exit status 69"
time="2024-01-31T04:43:27Z" level=info msg="Rendering sexbabesvr-265"
time="2024-01-31T04:43:58Z" level=info msg="Rendering slr-9770"
time="2024-01-31T04:43:58Z" level=warning msg="exit status 1"
time="2024-01-31T04:43:58Z" level=info msg="Rendering slr-9322"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x1078272]

goroutine 62468 [running]:
github.com/xbapps/xbvr/pkg/tasks.RenderPreview({0xc00120d980, 0x56}, {0xc000403c20, 0x2d}, {0x0, 0x0}, 0xa, 0x3fd999999999999a, 0x14, 0x1?, ...)
        /go/src/pkg/tasks/preview.go:79 +0x1f2
github.com/xbapps/xbvr/pkg/tasks.GeneratePreviews(0x0)
        /go/src/pkg/tasks/preview.go:39 +0x65d
created by github.com/xbapps/xbvr/pkg/api.TaskResource.previewGenerate in goroutine 61770
        /go/src/pkg/api/tasks.go:205 +0x1a
`

**Comment by theRealKLH** [comment]
Those exit 1s & exit 69s are errors from ffmpeg (not xbvr). The panic is probably ffmpeg choking on a vid (scene slr-9322 in this case) it can't handle. OR you ran out of memory. I would see if any of those scenes have previews. If not, it would be a good indicator that the videos are borked in some way.

**Comment by bkeeny5** [comment]
First of all thank you for this awesome software! I really like it a lot.

I've got a similar issue like the one above while trying to create previews. For EVERY video in my library I get
`xbvr-1  | time="2024-10-08T13:38:42Z" level=info msg="Rendering [video-id]"
xbvr-1  | time="2024-10-08T13:38:42Z" level=warning msg="signal: segmentation fault"`
with video-id changing accordingly with every video. 

Furthermore I get for every video in my library like @mescon above:
`xbvr-1  | time="2024-10-08T13:27:27Z" level=error msg="Error running ffprobe/videos/[filename]signal: segmentation fault" task=rescan`
with filename changing for each video. There's a space missing between ffprobe and path and filename and "signal" but my guess is that's only in the log message.

ffmpeg and ffprobe are in the config/xbvr/bin directory.

I run xbvr 0.4.31 in a docker container. The video directory is mounted as volume, so is the config directory. The rest of the installation is working fine and I can stream videos and funscripts to my headset perfectly. 

Help would very much be appreciated! Thank you in advance!

**Comment by bkeeny5** [comment]
Okay, so I found the solution myself. For some reason there was a faulty version of ffprobe in the config folder. It was only 19mb in size and always returned "segmentation fault" no matter which parameters I used (even for -L for showing the license). After exchanging it for a freshly downloaded ffprobe (~78mb in size) everything works now. So maybe this is of help for somebody somewhere sometime.
