### ISSUE TITLE
SIGSEGV with 0.4.23 in vrphub scraper

### ISSUE THREAD

**Issue by xnrfn** [xbapps/xbvr#1693]
Updated from 0.4.22, now crashing on a scraper. Probably the new code?

```
time="2024-04-04T01:13:22+02:00" level=info msg="visiting https://virtualrealporn.com/?videoPage=11"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf81829]

goroutine 3436 [running]:
github.com/xbapps/xbvr/pkg/scrape.ScraperRateLimiterCheckErrors(...)
	/go/src/pkg/scrape/scrape_rate_limiter.go:70
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func3(0xc0201fcae0)
	/go/src/pkg/scrape/vrphub.go:196 +0x429
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc024438b10)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0242dc540, 0xc02181bbd8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc018d2d880)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc0314923f0?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc023ebde30, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc031610090, 0x2c}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000ca7080?, {0xc031610090?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc01fa573e0)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc023ebdda0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc023ebdce0, 0xc02181c080)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc018d2d2c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc031492000?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc0238c4bd0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc030f75f80, 0x2c}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000ca6f00?, {0xc030f75f80?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc01f8776e0)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc0238c4b40)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0238c4a80, 0xc02181c528)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc018d2cd80)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc00a2c5b90?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc022d7e750, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc030f05cb0, 0x2c}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00af45000?, {0xc030f05cb0?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc01f7a15c0)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc022d7e6f0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc022d7e5a0, 0xc02181c9d0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc018d2c740)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc02fc8db00?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc0224cea20, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc030b498f0, 0x2c}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00af44680?, {0xc030b498f0?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc01e46d1a0)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc0224ce810)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0224ce780, 0xc02181ce78)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc00c514840)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc02fc8cc60?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc021b3c420, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc0300eb860, 0x2c}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00af44480?, {0xc0300eb860?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc014716e40)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc021b3c390)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc021b3c270, 0xc02181d320)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc00c5142c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc02fc8c870?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc02123a060, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc02feef8c0, 0x2c}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00af44100?, {0xc02feef8c0?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc014384d20)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc02171ffb0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc02171fef0, 0xc02181d7c8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc00b193dc0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc02fc8c480?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc020fe4ab0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc02fcf5b00, 0x2c}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00b043c80?, {0xc02fcf5b00?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
...150 frames elided...
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc013228240)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc0177881b0?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc0173fd950, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc0173e3bc0, 0x2b}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00af9df00?, {0xc0173e3bc0?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc0173f5860)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc0173fd8f0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0173fd860, 0xc0218242e0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc0126822c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc0085790e0?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc013c8c2d0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc013875200, 0x2b}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00adaca80?, {0xc013875200?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc01387d680)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc013c8c270)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc013c8c1e0, 0xc021824788)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc00aac7f00)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc004ee8ea0?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc010acc9c0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc010ac2f90, 0x2b}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000130180?, {0xc010ac2f90?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc010ad0720)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc010acc960)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc010acc8d0, 0xc021824c30)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc00c515300)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc00da7a2d0?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc00da70ab0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc00da55a40, 0x2b}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00af44f80?, {0xc00da55a40?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc00da76180)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc00da70a50)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc00da709c0, 0xc0218250d8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc0007e3780)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc002b5d170?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc004dd4b70, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc0063532f0, 0x24}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00b122180?, {0xc0063532f0?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc0046e5f80)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc004dd4a80)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc004dd4a20, 0xc021825580)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc00af92540)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc00360e120?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x3?, 0xc003601320, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc00a2a02a0, 0x2b}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00b042c00?, {0xc00a2a02a0?, 0x58?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.VRPHub.func2(0xc003606a20)
	/go/src/pkg/scrape/vrphub.go:169 +0xde
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x34e8920?, 0xc0036012c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc003601290, 0xc021825a28)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.1/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00aeb0c40, 0xc00b09aa00)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00aeb0c40, {0xa?, 0xc00b0b66c0?}, {0x153a80d, 0x3}, 0x1, {0x0?, 0x0}, 0x4?, 0xc00baf4c00, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00aeb0c40, {0xc0006fcff0, 0x23}, {0x153a80d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0x15aca01?, {0xc0006fcff0?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x15542d1, 0xa}, 0xc00b029e10, {0xc0006fcff0, 0x23})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.VRPHub(0x9632ae?, 0x1, {0xc00ac1e000, 0x5bb4, 0x5c00}, 0xc00aa1f620, {0x0, 0x0}, {0xc0006ed840, 0xd}, ...)
	/go/src/pkg/scrape/vrphub.go:206 +0x487
github.com/xbapps/xbvr/pkg/scrape.addVRPHubScraper.func1(0x963680?, 0x80?, {0xc00ac1e000, 0x5bb4, 0x5c00}, 0x0?, {0x0?, 0xc000b08f60?}, {0x0, 0x0}, ...)
	/go/src/pkg/scrape/vrphub.go:265 +0xe5
github.com/xbapps/xbvr/pkg/tasks.runScrapers.func1({{0xc0006ed840, 0xd}, {0xc00073a000, 0x10}, {0xc000642e70, 0x62}, {0x15542d1, 0xa}, 0xc0006a1d10, {0x0, ...}})
	/go/src/pkg/tasks/content.go:131 +0x63
created by github.com/xbapps/xbvr/pkg/tasks.runScrapers in goroutine 3294
	/go/src/pkg/tasks/content.go:130 +0x6b8
```

**Comment by moToroTor** [comment]
This looks fixed upstream by e376fa4 (#1690) — the nil guard in ScraperRateLimiterCheckErrors is present in current master. If the scrape crash is gone, could this be closed?
