### ISSUE TITLE
Failure adding scraped scenes to search index

### ISSUE THREAD

**Issue by thompc8** [xbapps/xbvr#1730]
I'm running on a Pi5 inside docker as per the instructions in the Readme and running the latest image, I've tried manually rebuilding the search index and had the same issue. This is a fresh setup as of a couple of days ago.

```
time="2024-05-16T07:49:50Z" level=info msg="Adding scraped scenes to search index..." task=scrape
panic: unaligned 64-bit atomic operation

goroutine 715763 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x71fe0dc, 0x0)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/blevesearch/zapx/v16.(*invertedIndexOpaque).incrementBytesWritten(...)
	/root/go/pkg/mod/github.com/blevesearch/zapx/v16@v16.0.12/section_inverted_text_index.go:401
github.com/blevesearch/zapx/v16.(*invertedIndexOpaque).writeDicts(0x71fe000, 0xa942288)
	/root/go/pkg/mod/github.com/blevesearch/zapx/v16@v16.0.12/section_inverted_text_index.go:529 +0xd84
github.com/blevesearch/zapx/v16.(*invertedTextIndexSection).Persist(0x3b7cec8, 0x4d23120, 0xa942288)
	/root/go/pkg/mod/github.com/blevesearch/zapx/v16@v16.0.12/section_inverted_text_index.go:54 +0x38
github.com/blevesearch/zapx/v16.(*interim).convert(0x4c4fab0)
	/root/go/pkg/mod/github.com/blevesearch/zapx/v16@v16.0.12/new.go:220 +0x6c8
github.com/blevesearch/zapx/v16.(*ZapPlugin).newWithChunkMode(0x3b7cec8, {0x588e6d0, 0x1, 0x1}, 0x402)
	/root/go/pkg/mod/github.com/blevesearch/zapx/v16@v16.0.12/new.go:69 +0x1b0
github.com/blevesearch/zapx/v16.(*ZapPlugin).New(0x3b7cec8, {0x588e6d0, 0x1, 0x1})
	/root/go/pkg/mod/github.com/blevesearch/zapx/v16@v16.0.12/new.go:45 +0x40
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Batch(0x4b12c00, 0x5a15320)
	/root/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.4.0/index/scorch/scorch.go:434 +0x62c
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Update(0x4b12c00, {0x3112c50, 0x4d04990})
	/root/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.4.0/index/scorch/scorch.go:355 +0x108
github.com/blevesearch/bleve/v2.(*indexImpl).Index(0x662aaf0, {0x5b9c800, 0xc}, {0x10e28c8, 0x103767e0})
	/root/go/pkg/mod/github.com/blevesearch/bleve/v2@v2.4.0/index_impl.go:260 +0x184
github.com/xbapps/xbvr/pkg/tasks.(*Index).PutScene(0x794f1f8, {0x23a1, {0x3572dca5, 0xeddd7b18e, 0x0}, {0x3c13a37, 0xeddd7b18f, 0x0}, 0x0, {0x5b9c800, ...}, ...})
	/go/src/pkg/tasks/search.go:97 +0x530
github.com/xbapps/xbvr/pkg/tasks.IndexScenes(0x4d4bbc0)
	/go/src/pkg/tasks/search.go:188 +0x3c0
github.com/xbapps/xbvr/pkg/tasks.IndexScrapedScenes(0x52ffaf0)
	/go/src/pkg/tasks/search.go:223 +0x168
github.com/xbapps/xbvr/pkg/tasks.Scrape({0x117a14e, 0x8}, {0x0, 0x0}, {0x0, 0x0})
	/go/src/pkg/tasks/content.go:367 +0x740
github.com/xbapps/xbvr/pkg/server.scrapeCron()
	/go/src/pkg/server/cron.go:84 +0x50
github.com/robfig/cron/v3.FuncJob.Run(0x2f51bf8)
	/root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1c
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6c
created by github.com/robfig/cron/v3.(*Cron).startJob in goroutine 61
	/root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xa4
```

**Comment by thompc8** [comment]
I was using latest [0.4.25] but pulling and running [0.4.24](https://github.com/orgs/xbapps/packages/container/xbvr/200021227?tag=0.4.24) seems to work and it's now indexing scenes.
It looks like there was a dependency update around the time of the last release to the latest blevesearch library, that could be related.
