### ISSUE TITLE
Crash on SexLikeReal scraper

### ISSUE THREAD

**Issue by moToroTor** [xbapps/xbvr#1779]
I'm not 100% sure why, but I get crashes when scraping SLR, I think it may be because it forces me to https://www.sexlikereal.com/all-age and I can't see any content unless I sign up, possibly due to me being in an anti-porn state that requires sites to check ID to access.

```
time="2024-07-11T00:03:06-05:00" level=info msg="Scraping started at Thu Jul 11 00:03:06 2024" task=scrape
time="2024-07-11T00:03:09-05:00" level=info msg="Starting  scraper" completed=false progress=0 scraperID= started=true task=scraperProgress
time="2024-07-11T00:03:09-05:00" level=info msg="visiting https://www.sexlikereal.com/scenes/first-threesome-with-sarah-34247"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x100b725dc]

goroutine 4953 [running]:
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func1(0xc000754d80)
	/go/src/pkg/scrape/slrstudios.go:155 +0xb3c
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x103182800?, 0xc002de99b0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc002de9980, 0xc002e3db60)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00033cc40, 0xc0006b6140)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00033cc40, {0xa?, 0xc00292d710?}, {0x1011ccd49, 0x3}, 0x1, {0x0?, 0x0}, 0xec0000c0029cf5f0?, 0xc002a0c540, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00033cc40, {0xc000542050, 0x43}, {0x1011ccd49, 0x3}, 0x1, {0x0, 0x0}, 0xc0029cf5f0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Request(...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:499
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal(0xe429582710444?, 0x1, {0xc003638000, 0x240b, 0x2c00}, 0xc000145f80, {0xc000542050, 0x43}, {0x0, 0x0}, ...)
	/go/src/pkg/scrape/slrstudios.go:413 +0x5d1
github.com/xbapps/xbvr/pkg/scrape.init.16.func1(0x200?, 0x1?, {0xc003638000?, 0x100c723b0?, 0xc0009da0b0?}, 0xc002cec000?, {0xc000542050?, 0x4000?}, {0xc000366438, 0x2}, ...)
	/go/src/pkg/scrape/slrstudios.go:551 +0x65
created by github.com/xbapps/xbvr/pkg/tasks.runScrapers in goroutine 4938
	/go/src/pkg/tasks/content.go:153 +0x925
```

**Comment by pops64** [comment]
SLR has a max connection limit now. Ensure you set the --concurrent_scrapers to four or less. Also use a VPN or a proxy to get around content blocking because of state ID laws

**Comment by moToroTor** [comment]
New issue or continuation? If this is a concurrent scrapers issue (I do not have it set so it's 9999), there's no environment flag for that for docker at the moment per #1449.

```
time="2024-09-01T20:05:22Z" level=info msg="visiting https://www.sexlikereal.com/scenes/wanking-service-23719"
time="2024-09-01T20:05:32Z" level=error msg="Error visiting https://www.sexlikereal.com/scenes/wanking-service-23719 context deadline exceeded (Client.Timeout or context cancellation while reading body)"
time="2024-09-01T20:05:32Z" level=info msg="visiting https://www.sexlikereal.com/scenes/undress-to-impress-23718"
time="2024-09-01T20:06:12Z" level=error msg="Method Head Failed on desktopCover  with error Head "": unsupported protocol scheme """
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xd1c262]
goroutine 454274 [running]:
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func1(0xc00416e480)
	/go/src/pkg/scrape/slrstudios.go:174 +0xf22
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc0041615c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc004161590, 0xc0047e5fb0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346540, 0xc006093200)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346540, {0xa?, 0xc003508f30?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x690000c000d215e0?, 0xc0038220c0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346540, {0xc0033dc900, 0x3b}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0xc000d215e0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Request(...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:499
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func3(0xc002e49260)
	/go/src/pkg/scrape/slrstudios.go:406 +0x78f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc00350df50)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0029db5f0, 0xc0047e6678)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc000a84380)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc003516630?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc0038df620, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc003861780, 0x48}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0038bb841?, {0xc003861780?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc001dcaa00, {0xc003861780, 0x48})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc0038e6c60)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc0038df5c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0038df530, 0xc0047e6bb0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc0008d8480)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc0044cf950?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc003055d70, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc003020300, 0x48}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00301ebe1?, {0xc003020300?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc001dcaf38, {0xc003020300, 0x48})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc003023980)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc003055d10)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc002ef4960, 0xc0047e70e8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc000946e00)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc000986f30?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc0028fd4a0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc0027c8180, 0x48}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0027acaa1?, {0xc0027c8180?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc001dcb470, {0xc0027c8180, 0x48})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc002553bc0)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc0028fd3e0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0028fd050, 0xc0047e7620)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc00404a780)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc002b8c870?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc00187a660, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc001e6a280, 0x48}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc001956dc1?, {0xc001e6a280?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc001dcb9a8, {0xc001e6a280, 0x48})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc0011ba3c0)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc00187a210)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0004fa570, 0xc0047e7b58)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc000416000)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc0044cf9e0?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc002b36930, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc002a8be80, 0x48}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc002b15321?, {0xc002a8be80?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc001dcbee0, {0xc002a8be80, 0x48})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc002b34ae0)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc002b368d0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc002b36720, 0xc0047e8090)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
...46 frames elided...
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc0013ead80)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0013eacf0, 0xc0047e9fe0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc00404b140)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc00333d9e0?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc00136c2d0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc002a98080, 0x48}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc001382461?, {0xc002a98080?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc006248368, {0xc002a98080, 0x48})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc0012596e0)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc00136c270)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc00215d5f0, 0xc0047ea518)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc0062be3c0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc000bbb5f0?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc00136c390, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc003003480, 0x47}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00134b541?, {0xc003003480?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc0062488a0, {0xc003003480, 0x47})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc00135f3e0)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc00136c330)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc00136c180, 0xc0047eaa50)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc000360e40)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc000ad6cf0?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc000bf72f0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc0029b4900, 0x47}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000eac121?, {0xc0029b4900?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc006248dd8, {0xc0029b4900, 0x47})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc0010803c0)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc000bf7230)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc000bf6f60, 0xc0047eaf88)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc000852380)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc000ad6480?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc000ba1c20, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc0017fdb80, 0x47}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000e91e01?, {0xc0017fdb80?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc0060fd310, {0xc0017fdb80, 0x47})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc001081bc0)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc000ba1bc0)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc000ba1ad0, 0xc0047eb4c0)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc000a84f40)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc00333c2d0?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc000cbe2d0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc000af8780, 0x47}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0004eff41?, {0xc000af8780?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc0060fd848, {0xc000af8780, 0x47})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal.func2(0xc0009714a0)
	/go/src/pkg/scrape/slrstudios.go:324 +0x11d
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x35361e0?, 0xc000cbe240)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x69
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc000cbe180, 0xc0047eb9f8)
	/root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.2/iteration.go:10 +0x4f
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000346c40, 0xc000360d00)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x210
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000346c40, {0xa?, 0xc006057cb0?}, {0x157382d, 0x3}, 0x1, {0x0?, 0x0}, 0x4?, 0xc0060f1a10, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x72d
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000346c40, {0xc0060d0740, 0x40}, {0x157382d, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x5df
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0060fdd18?, {0xc0060d0740?, 0x0?})
	/root/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0xa5
github.com/xbapps/xbvr/pkg/scrape.WaitBeforeVisit({0x159e28f, 0x13}, 0xc0060fde08, {0xc0060d0740, 0x40})
	/go/src/pkg/scrape/scrape_rate_limiter.go:57 +0x44
github.com/xbapps/xbvr/pkg/scrape.SexLikeReal(0x3d?, 0x1, {0xc0061e2000, 0x3a0f, 0x4800}, 0xc00601f560, {0x0, 0x0}, {0xc000015630, 0xf}, ...)
	/go/src/pkg/scrape/slrstudios.go:420 +0x63a
github.com/xbapps/xbvr/pkg/scrape.addSLRScraper.func1(0x4?, 0x40?, {0xc0061e2000, 0x1?, 0x4800}, 0x0?, {0x0?, 0xc000827f68?}, {0x0, 0x0}, ...)
	/go/src/pkg/scrape/slrstudios.go:542 +0xcd
github.com/xbapps/xbvr/pkg/tasks.runScrapers.func1({{0xc000015630, 0xf}, {0xc0005a5128, 0x18}, {0x15e229c, 0x4f}, {0x159681c, 0xf}, 0xc00058de00, {0x0, ...}})
	/go/src/pkg/tasks/content.go:131 +0x63
created by github.com/xbapps/xbvr/pkg/tasks.runScrapers in goroutine 454174
	/go/src/pkg/tasks/content.go:130 +0x6b8

```

**Comment by pops64** [comment]
Please open a new issue and provide either the scene or the studio it is crashing on. As I am only taking stabs in the dark at how to fix this as the one time I encountered this issue was a DNS failure on my network.
