### ISSUE TITLE
XBVR crashes if videos are played to the end via DeoVR

### ISSUE THREAD

**Issue by mbalax11** [xbapps/xbvr#475]
Sometimes XBVR crashes if I let the video play to the end. This does not happen if I end the video earlier.

Here's the log:

```
[454078]  INFO Session #15528 duration for scene #6223 is 488.706044407
[454078]  INFO New session #15529 for scene #3590 from deovr
[454559]  INFO Session #15529 duration for scene #3590 is 481.083851922
[454571]  INFO New session #15530 for scene #6026 from file
[454661]  INFO Session #15530 duration for scene #6026 is 90.529203263
[454664]  INFO New session #15531 for scene #5929 from file
[454678]  INFO Session #15531 duration for scene #5929 is 13.876269287
[454678]  INFO New session #15532 for scene #1878 from deovr
panic: runtime error: index out of range

goroutine 5582605 [running]:
github.com/xbapps/xbvr/pkg/session.TrackSessionFromRemote(0xc003e72340, 0x34, 0x4081711eb851eb85, 0x40817015182a9931, 0x3ff0000000000000, 0x0)
        /go/appsrc/pkg/session/session.go:96 +0x3c5
created by github.com/xbapps/xbvr/pkg/session.deoLoop
        /go/appsrc/pkg/session/remote.go:77 +0x9a4
```

**Comment by mbalax11** [comment]
Could it be that `packet.CurrentTime` is -1 or something when the video ends [here](https://github.com/xbapps/xbvr/blob/master/pkg/session/session.go#L94)?
